// All editable content lives here. main.js renders the page from it.

export const site = {
  name: 'Elenor Developing Team',
  title: 'Full-Stack & AI Engineering',
  location: 'Cairo, Egypt',
  intro:
    'We design and build production software end to end — marketing sites with a CMS behind them, internal platforms that run a company, mobile apps, and AI agents that do real work.',
  about: [
    'We work across the whole stack: the database schema, the server that guards it, and the interface people actually touch. The projects below range from a cinematic agency website to an ERP that handles Egyptian VAT and e-invoicing, to autonomous agents that crawl, score and report.',
    'What ties them together is a preference for systems that are provably correct — the server computes the totals, authorization is checked on every request, and the tests run against a real database rather than mocks.',
  ],
  stats: [
    { value: '9', label: 'Featured products' },
    { value: '17', label: 'Modules in one ERP' },
    { value: '235', label: 'Automated tests on one system' },
    { value: 'AR · EN', label: 'Bilingual, RTL-aware UIs' },
  ],
  capabilities: ['Web platforms & CMS', 'Internal tools & ERP', 'AI agents & automation', 'Mobile apps'],
  // Add more entries (GitHub, LinkedIn, …) and they appear in the Contact section.
  links: [
    { label: 'Email', href: 'mailto:info@elenor-marketing.com', text: 'info@elenor-marketing.com' },
    { label: 'WhatsApp +20 12 01137272', href: 'https://wa.me/201201137272' },
  ],
  email: 'info@elenor-marketing.com',
};

const img = (slug, name, w, h, alt, kind = 'desktop') => ({
  name,
  src: `assets/img/${slug}/${name}-${kind === 'phone' ? 720 : 1600}.webp`,
  srcSmall: `assets/img/${slug}/${name}-${kind === 'phone' ? 360 : 800}.webp`,
  w,
  h,
  alt,
  kind,
});

// `featured` (screenshot numbers) picks the shots shown on the scrolling timeline; the rest are
// one click away in the viewer. Leave it out to show every shot.
export const projects = [
  {
    id: 'elenor-website',
    title: 'Elenor Website',
    category: 'Marketing site + custom CMS',
    accent: '#45d0d3',
    summary:
      'A cinematic, 3D scroll-driven site for a Cairo marketing agency — backed by a custom database CMS so a non-technical team can edit every page, service, case study and colour, live, with no rebuilds.',
    features: [
      'Admin dashboard at /admin with Super Admin and Editor roles',
      'SEO / GEO / AEO: JSON-LD, sitemap and llms.txt generated from the database',
      'Draft preview, scheduled posts and tag-based cache revalidation',
      'Drag-and-drop media library with automatic WebP compression',
    ],
    highlights: ['SEO', 'GEO / AEO', 'Custom CMS', 'Live editing, no rebuilds', '3D scroll experience', 'Role-based admin', 'Scheduled publishing', 'AI chat assistant'],
    stack: ['Next.js', 'React Three Fiber', 'GSAP', 'Lenis', 'Tailwind', 'Postgres · Neon', 'Drizzle', 'Tiptap', 'Vercel Blob'],
    layout: 'desktop',
    featured: ['01', '02', '04', '05', '15', '18', '22', '23'],
    lead: img('elenor-website', '01', 1600, 870, 'Elenor website hero: “Where innovation meets quality”'),
    gallery: [
      img('elenor-website', '02', 1600, 869, 'Scroll-driven showcase of client work and orbiting logos'),
      img('elenor-website', '03', 1600, 873, 'Philosophy: credibility, flexibility, fast response and creativity'),
      img('elenor-website', '04', 1600, 870, 'Work browsed one discipline at a time'),
      img('elenor-website', '05', 1600, 872, 'Proof in numbers, with client testimonials'),
      img('elenor-website', '06', 1600, 870, 'Latest articles from the studio blog'),
      img('elenor-website', '07', 1600, 867, 'Closing call to action and footer'),
      img('elenor-website', '08', 1600, 870, 'About page'),
      img('elenor-website', '09', 1600, 875, 'A word from the CEO'),
      img('elenor-website', '10', 1600, 873, '“What tailored actually means” — the agency’s approach'),
      img('elenor-website', '11', 1600, 876, 'Brand philosophy: vision, mission, values and goals'),
      img('elenor-website', '12', 1600, 873, 'FAQ and call to action on the About page'),
      img('elenor-website', '13', 1600, 863, 'Services page with an animated icon constellation'),
      img('elenor-website', '14', 1600, 869, 'All ten services at a glance'),
      img('elenor-website', '15', 1600, 866, 'Service detail: Brand Identity, what’s included and the process'),
      img('elenor-website', '16', 1600, 867, 'Work page, filterable by industry'),
      img('elenor-website', '17', 1600, 866, 'Case studies filtered across industries'),
      img('elenor-website', '18', 1600, 873, 'Case study: Coca-Cola'),
      img('elenor-website', '19', 1600, 870, 'Blog: “Insights. Not filler.”'),
      img('elenor-website', '20', 1600, 875, 'Blog articles grouped by topic'),
      img('elenor-website', '21', 1600, 868, 'FAQ page grouped by subject'),
      img('elenor-website', '22', 1600, 868, 'Contact form, direct details and map'),
      img('elenor-website', '23', 685, 829, 'Elenor AI chat assistant'),
    ],
  },
  {
    id: 'elenor-os',
    title: 'Elenor OS',
    category: 'Internal operations platform',
    accent: '#06b6d4',
    summary:
      'The operating system for a marketing agency: tasks, projects, people, approvals, leave, performance and company policy in one branded, permission-secured product.',
    features: [
      'Kanban, list, table and calendar task views with subtasks and dependencies',
      'Granular RBAC: role matrix plus per-user allow / deny overrides',
      'Multi-level leave, permission and resignation approval chains',
      'Weighted Employee-of-the-Month engine, audit log and ⌘K command palette',
    ],
    highlights: ['Tasks Module', 'Approval workflows', 'Sales pipeline & CRM', 'Performance analytics', 'Audit log', '⌘K command palette','HR Module','Light / dark mode'],
    stack: ['Next.js 15', 'TypeScript', 'PostgreSQL', 'Prisma', 'JWT + refresh rotation', 'TanStack Query', 'Framer Motion', 'Recharts'],
    layout: 'desktop',
    featured: ['01', '02b', '03', '04', '21', '38', '40', '42'],
    lead: img('elenor-os', '01', 1600, 873, 'Dashboard with KPIs, Employee of the Month and task trend'),
    gallery: [
      img('elenor-os', '02', 1600, 871, 'Task board across workflow statuses'),
      img('elenor-os', '02b', 1600, 878, 'Task board with work moving through editing and done'),
      img('elenor-os', '03', 1600, 880, 'Projects with progress and deadlines'),
      img('elenor-os', '04', 1600, 869, 'Sales dashboard: pipeline funnel, lead sources and forecast'),
      img('elenor-os', '05', 1600, 867, 'Leads, filterable by stage, priority, source and owner'),
      img('elenor-os', '06', 795, 953, 'New lead form with contact and pipeline details'),
      img('elenor-os', '07', 1600, 868, 'Pipeline board from new lead to proposal'),
      img('elenor-os', '08', 1600, 873, 'Discovery briefs'),
      img('elenor-os', '09', 539, 657, 'Writing a discovery brief against a lead'),
      img('elenor-os', '10', 1600, 869, 'Meetings booked with prospects'),
      img('elenor-os', '11', 779, 980, 'Scheduling a meeting with agenda and attendees'),
      img('elenor-os', '12', 1600, 873, 'Sales feedback grouped by how hot each opportunity is'),
      img('elenor-os', '13', 834, 951, 'Post-meeting feedback with a calculated opportunity score'),
      img('elenor-os', '14', 777, 939, 'Client read, recommended services and next steps'),
      img('elenor-os', '15', 1600, 868, 'Proposal centre'),
      img('elenor-os', '16', 712, 705, 'Creating a proposal'),
      img('elenor-os', '17', 1600, 869, 'Converted clients with deal values'),
      img('elenor-os', '18', 1600, 868, 'Activity feed across the pipeline'),
      img('elenor-os', '19', 1600, 876, 'Ideas board'),
      img('elenor-os', '20', 652, 720, 'Adding an idea linked to a lead or client'),
      img('elenor-os', '21', 1600, 873, 'Sales reports: win rate, revenue and growth'),
      img('elenor-os', '22', 1600, 870, 'Pipeline forecast, lead sources and source mix'),
      img('elenor-os', '23', 1600, 876, 'Industries, salesperson performance and quarterly growth'),
      img('elenor-os', '24', 1600, 867, 'Sales team leaderboard'),
      img('elenor-os', '25', 1600, 868, 'Sales team performance'),
      img('elenor-os', '26', 1600, 871, 'Client directory'),
      img('elenor-os', '27', 606, 702, 'Adding a client'),
      img('elenor-os', '28', 1600, 877, 'Task approvals waiting on a decision'),
      img('elenor-os', '29', 1600, 869, 'Leave requests'),
      img('elenor-os', '30', 592, 643, 'Requesting leave with a work handover'),
      img('elenor-os', '31', 1600, 873, 'Permission requests'),
      img('elenor-os', '32', 634, 511, 'Requesting a late-arrival permission'),
      img('elenor-os', '33', 1600, 872, 'Employee directory'),
      img('elenor-os', '34', 625, 815, 'Adding an employee with role, manager and job description'),
      img('elenor-os', '35', 1600, 872, 'Departments'),
      img('elenor-os', '36', 646, 452, 'Creating a department'),
      img('elenor-os', '37', 1600, 868, 'Performance: completion trend, workload and priorities'),
      img('elenor-os', '38', 1600, 869, 'Employee of the Month leaderboard'),
      img('elenor-os', '39', 574, 514, 'Adjusting the Employee-of-the-Month scoring weights'),
      img('elenor-os', '40', 1600, 868, 'Company policies with acknowledgement tracking'),
      img('elenor-os', '41', 1600, 867, 'Job descriptions'),
      img('elenor-os', '42', 1600, 871, 'Dashboard in light mode with notifications open'),
    ],
  },
  {
    id: 'ERP-erp',
    title: 'ERP Business OS',
    category: 'Storage · HR · Accounting ERP',
    accent: '#6b9bff',
    summary:
      'A 17-module ERP built for the Egyptian market — inventory, billing, clients, projects and HR — where the server is the single source of truth for every figure.',
    features: [
      'Ledger-based stock: every movement is appended, never overwritten',
      'ETA e-invoice documents with per-line 14% VAT and withholding tax',
      'Geofenced attendance re-verified on the server against the site location',
      '235 tests against the real database and browser, desktop and mobile',
    ],
    highlights: ['Accounting Module', 'Warehouse Module', 'Geofenced attendance', 'HR Module', 'Arabic / RTL', '235 automated tests'],
    stack: ['Next.js 15', 'TypeScript', 'Prisma 7', 'Neon Postgres', 'argon2id', 'Playwright', 'Arabic / RTL'],
    layout: 'desktop',
    featured: ['01', '03', '05', '11', '13', '18', '22', '25'],
    lead: img('gts-erp', '01', 1600, 865, 'Executive dashboard: items needing attention, net position and cash'),
    gallery: [
      img('gts-erp', '02', 1600, 865, 'Your work, warehouses, attendance and recent activity'),
      img('gts-erp', '03', 1600, 861, 'Accounts: receivables and payables with ageing'),
      img('gts-erp', '04', 1600, 870, 'Electronic bills with 14% VAT'),
      img('gts-erp', '05', 1600, 867, 'Drafting an e-invoice with line items, VAT and withholding tax'),
      img('gts-erp', '06', 1600, 870, 'Payments ledger'),
      img('gts-erp', '07', 1600, 862, 'Clients with outstanding balances'),
      img('gts-erp', '08', 1600, 865, 'Adding a client with its tax registration number'),
      img('gts-erp', '09', 1600, 873, 'Vendors'),
      img('gts-erp', '10', 1600, 866, 'Adding a vendor'),
      img('gts-erp', '11', 1600, 871, 'Projects with sites, budgets and billing'),
      img('gts-erp', '12', 1600, 860, 'Creating a project'),
      img('gts-erp', '13', 1600, 867, 'Pinning a project site on the map with a check-in radius'),
      img('gts-erp', '14', 1600, 856, 'Assigning employees to a project'),
      img('gts-erp', '15', 1600, 873, 'Allocating stock from a warehouse to a project'),
      img('gts-erp', '16', 1600, 870, 'Warehouses with stock on hand'),
      img('gts-erp', '17', 1600, 873, 'Adding a warehouse'),
      img('gts-erp', '18', 1600, 870, 'Product catalogue with cost, sale price and reorder levels'),
      img('gts-erp', '19', 1600, 867, 'Adding a product'),
      img('gts-erp', '20', 1600, 867, 'Employee directory'),
      img('gts-erp', '21', 1600, 866, 'Adding an employee'),
      img('gts-erp', '22', 1600, 866, 'Geofenced attendance check-in'),
      img('gts-erp', '23', 1600, 853, 'Leave balances and requests'),
      img('gts-erp', '24', 1600, 866, 'Leave approvals and who is away today'),
      img('gts-erp', '25', 1600, 867, 'Reports: invoiced, cash moved and VAT position'),
      img('gts-erp', '26', 1600, 866, 'User accounts and roles'),
      img('gts-erp', '27', 1600, 863, 'Permission matrix for the Employee role'),
      img('gts-erp', '28', 1600, 869, 'Permission matrix for the Financial controller role'),
    ],
  },
  {
    id: 'geo-audit',
    title: 'GEO Audit Platform',
    category: 'AI visibility auditing',
    accent: '#7b93ff',
    summary:
      'Automated Generative Engine Optimization audits: crawl a site, understand the business behind it, and score how well it will surface in ChatGPT, Perplexity, Gemini and Google AI Overviews.',
    features: [
      'Playwright crawler with sitemap, robots.txt and JavaScript rendering',
      'Classifies 16 page types and extracts entities with evidence',
      'Fact-consistency engine flags conflicting business details',
      'Explainable 0–100 score across 10 categories, exported to PDF / DOCX',
    ],
    highlights: ['GEO', 'AI search visibility', 'Technical SEO audit', 'Entity extraction', 'Fact-consistency checks', 'Explainable scoring', 'PDF / DOCX reports'],
    stack: ['Next.js 15', 'TypeScript', 'Playwright', 'Cheerio', 'Prisma', 'Neon', 'OpenAI', 'PDFKit'],
    layout: 'desktop',
    lead: img('geo-audit', '01', 1600, 869, 'GEO Audit Platform start screen'),
    gallery: [
      img('geo-audit', '02', 1600, 873, 'Crawling the website'),
      img('geo-audit', '03', 1600, 868, 'Extracting entities and flagging fact-consistency issues'),
      img('geo-audit', '04', 1600, 535, 'Overall GEO score with category breakdown'),
      img('geo-audit', '05', 1600, 824, 'Crawled pages classified by type with scores'),
      img('geo-audit', '06', 1600, 814, 'Issues grouped by severity'),
      img('geo-audit', '07', 1600, 817, 'Recommendations for each issue'),
      img('geo-audit', '08', 1600, 826, 'Report export to PDF, DOCX, Markdown and JSON'),
    ],
  },
  {
    id: 'agent-x',
    title: 'Agent X',
    category: 'Competitor-intelligence agent',
    accent: '#4ade80',
    summary:
      'An agent that watches competitors’ websites, feeds and news and turns verified business changes into evidence-backed intelligence — a daily digest and a weekly trend report by email.',
    features: [
      'Deterministic change detection — the LLM never decides whether something changed',
      'Changes are confirmed only when they persist across days',
      'Capped 0–10 scoring into ignore / monitor / notable / urgent buckets',
      'LLM output validated three ways, with a deterministic fallback',
    ],
    highlights: ['Competitor intelligence', 'Change detection', 'Evidence-backed insights', 'Daily & weekly digests', 'Validated LLM output', 'Deterministic fallback'],
    stack: ['Python 3.11', 'uv', 'PostgreSQL · Neon', 'Playwright', 'OpenRouter', 'Pydantic', 'pytest'],
    layout: 'pipeline',
    pipeline: ['Fetch', 'Verify', 'Normalize', 'Fingerprint', 'Detect', 'Score', 'Interpret', 'Digest'],
  },
  {
    id: 'adlens',
    title: 'AdLens',
    category: 'MCP server for ad research',
    accent: '#f59e6b',
    summary:
      'An MCP server that lets Claude research competitors’ advertising: it scrapes the public Meta Ads Library, keeps a swipe file of the ads worth saving, and analyses them for brand DNA and fresh hook ideas.',
    features: [
      'Zero external API keys — Playwright, the local file system and the host’s own LLM',
      'Headless scraping of public Meta Ads Library results, no login or bypassing',
      'Persistent local swipe file, exposed as an MCP resource',
      'Brand-DNA analysis and ad-hook generation through MCP sampling',
    ],
    highlights: ['MCP server', 'Ad research', 'Swipe file', 'Brand-DNA analysis', 'Hook generation', 'Zero API keys'],
    stack: ['TypeScript', 'Node.js', 'Model Context Protocol', 'Playwright', 'Claude Desktop / Code'],
    layout: 'desktop',
    lead: img('adlens', '01', 940, 770, 'Claude asking permission to run AdLens’s scrape_ad_library tool'),
  },
  {
    id: 'church-app',
    title: 'Church QR Attendance',
    category: 'iOS & Android app',
    accent: '#8b93f8',
    summary:
      'A bilingual mobile app for QR-based attendance: members carry a personal code, admins scan it at meetings, and leaders see attendance and activity at a glance.',
    features: [
      'Role-based apps for members, admins and super admins',
      'Meeting windows that open the scanner automatically',
      'Arabic and English with full RTL support and dark mode',
      'Secure token storage and offline-friendly server state',
    ],
    highlights: ['QR attendance', 'iOS & Android', 'Role-based access', 'Arabic / RTL', 'Dark mode', 'Offline-friendly'],
    stack: ['React Native', 'Expo SDK 52', 'Expo Router', 'NativeWind', 'Reanimated', 'Zustand', 'TanStack Query'],
    layout: 'phones',
    phones: [
      img('church-app', 'meetings', 720, 1591, 'Meetings schedule', 'phone'),
      img('church-app', 'dashboard', 720, 1591, 'Super admin dashboard with members and weekly attendance', 'phone'),
      img('church-app', 'profile', 720, 1591, 'Profile with QR code, theme and language', 'phone'),
    ],
    gallery: [img('church-app', 'attendance', 720, 1591, 'Weekly attendance and recent activity', 'phone')],
  },
  {
    id: 'herts-quest',
    title: 'Herts Quest',
    category: 'Campus treasure-hunt game',
    accent: '#c084fc',
    summary:
      'A gamified treasure hunt for the University of Hertfordshire: students scan QR codes around campus, solve trivia and photo puzzles, and race up a live leaderboard.',
    features: [
      'QR codes generated and printed from the admin dashboard',
      'Trivia categories and photo puzzles with scoring',
      'Live leaderboard that refreshes every few seconds',
      'Admin control centre for hubs, puzzles, players and submissions',
    ],
    highlights: ['Gamification', 'QR scanning', 'Live leaderboard', 'Photo puzzles', 'Admin control centre', 'Mobile-first'],
    stack: ['Next.js 14', 'TypeScript', 'Tailwind CSS', 'Prisma', 'SQLite', 'qrcode'],
    layout: 'desktop',
    featured: ['01', '02', '04', '05', '06', '08', '10'],
    lead: img('herts-quest', '01', 600, 1326, 'Herts Quest start screen', 'phone'),
    gallery: [
      img('herts-quest', '02', 600, 1326, 'Scanning a quest QR code', 'phone'),
      img('herts-quest', '03', 600, 1326, 'Starting a trivia quiz', 'phone'),
      img('herts-quest', '04', 600, 1326, 'Choosing a challenge at a game hub', 'phone'),
      img('herts-quest', '05', 600, 1326, 'Answering a trivia question', 'phone'),
      img('herts-quest', '06', 1600, 869, 'Admin operations overview'),
      img('herts-quest', '07', 1600, 871, 'Campus game hubs with their QR codes'),
      img('herts-quest', '08', 1600, 876, 'Admin: photo puzzles'),
      img('herts-quest', '09', 1600, 871, 'Admin: trivia categories'),
      img('herts-quest', '10', 1600, 874, 'Admin: trivia question bank'),
      img('herts-quest', '11', 1600, 862, 'Admin: player management'),
    ],
  },
  {
    id: 'off-script',
    title: 'Off Script',
    category: 'E-commerce customization platform',
    accent: '#e85d2a',
    summary:
      'A digital creative workshop for product customization: a "junk journal" design canvas, live 3D product preview and an AI creative partner, so picking a mug or hoodie feels like making something rather than filling out a form.',
    features: [
      'Layer-based canvas for text, stickers, images and shapes on every product',
      'Live 3D product preview that updates directly from the 2D design canvas',
      'Conversational AI creative partner for ideation, remixing and layout',
      'Full commerce flow: catalogue, cart, checkout and an order dashboard',
    ],
    highlights: ['3D product preview', 'AI creative partner', 'Design canvas', 'E-commerce flow', 'Community explore feed', 'Brand system'],
    stack: ['Next.js', 'React Three Fiber', 'Tailwind CSS', 'Fabric.js / Canvas API', 'Claude API'],
    layout: 'desktop',
    featured: ['01', '02', '04', '06', '08', '10'],
    lead: img('off-script', '01', 388, 478, 'Landing page: “Make it yours” with a 3D custom mug'),
    gallery: [
      img('off-script', '02', 287, 451, 'Product catalogue: mugs, hoodies, tote bags, phone cases and more'),
      img('off-script', '03', 318, 461, 'Design editor with text, image, sticker, shape and layer tools'),
      img('off-script', '04', 278, 455, '3D product view with material picker and 360° preview'),
      img('off-script', '05', 237, 458, 'AI creative partner suggesting on-brand design ideas'),
      img('off-script', '06', 290, 395, 'Checkout with shipping address and order summary'),
      img('off-script', '07', 363, 382, 'Account dashboard: orders, saved designs and credits'),
      img('off-script', '08', 343, 389, 'Explore feed of community designs, featured and trending'),
      img('off-script', '09', 242, 382, 'Product detail with add-ons, quantity and add to cart'),
      img('off-script', '10', 282, 377, 'Mobile: landing screen and in-progress design editor'),
    ],
  },
];
